# Generated by Django 3.1.6 on 2021-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210219_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.TextField(default=None),
        ),
    ]
