# Generated by Django 3.1.6 on 2021-04-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answer',
        ),
    ]
