# Generated by Django 3.1.6 on 2021-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='target',
            field=models.SlugField(default=None),
        ),
    ]
