# Generated by Django 3.1.6 on 2021-04-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_answer_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='posts.post'),
        ),
    ]
