# Generated by Django 3.1.6 on 2021-04-03 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20210401_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='commenter',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
