# Generated by Django 3.1.6 on 2021-02-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_name',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='id_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
