# Generated by Django 3.1.6 on 2021-02-19 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_id_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='other_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
    ]
