# Generated by Django 3.1.6 on 2021-02-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210221_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follower_slug',
            field=models.SlugField(default=None),
        ),
    ]
