# Generated by Django 3.1.6 on 2021-03-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_follow_follower_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_following',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_slug',
            field=models.SlugField(default='<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
