# Generated by Django 3.1.6 on 2021-04-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210331_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_following',
        ),
    ]
